model_name_or_path: ./biobert/model   # your local BioBERT path
tokenizer_path: ./biobert/tokenizer   # your local tokenizer path
output_dir: results/finetuned_biobert
epochs: 5
batch_size: 8
learning_rate: 2e-5